### ISSUE TITLE
Build with Kali 1.0.7

### ISSUE THREAD

**Issue by fe8769** [szechyjs/dsd#40]
hello 

error in DSD make command

git clone https://github.com/LinuxSheeple-E/dsd
cd dsd
git checkout Feature/DMRECC

cd dsd
mkdir build
cd build
cmake ..
make

error 

/usr/local/include/itpp/base/itassert.h:34:28: fatal error: itpp/itexports.h: Aucun fichier ou dossier de ce type
/usr/local/include/itpp/itbase.h:128:36: fatal error: itpp/base/base_exports.h: Aucun fichier ou dossier de ce type
/usr/local/include/itpp/itcomm.h:75:39: fatal error: itpp/comm/multilateration.h: Aucun fichier ou dossier de ce type

in french no file found : to resolve need to copy the specific file in the specific library

Second set of errors 

/usr/local/lib/libitpp.so: undefined reference to `itpp::g711_details::MuLaw_Properties::expansion_table'
/usr/local/lib/libitpp.so: undefined reference to`itpp::g711_details::G711_Base_Properties::compression_table'
/usr/local/lib/libitpp.so: undefined reference to `itpp::g711_details::ALaw_Properties::expansion_table'

problem with g711.cpp ? but what 

thanks for answer

**Comment by jcabbott86** [comment]
i copy pasted all the the commands and i still get errors.. 
i ran..

apt-get update
apt-get upgrade

everything worked upto..

cd itpp-4.3.1
mkdir build && cd build
cmake ..
make -j'nproc'
sudo make install
 ERROR OUTPUT
__________________________________
[  1%] Building CXX object itpp/CMakeFiles/itpp.dir/base/random.cpp.o
In file included from /root/itpp-4.3.1/itpp/base/random_dsfmt.h:40:0,
                 from /root/itpp-4.3.1/itpp/base/random.h:32,
                 from /root/itpp-4.3.1/itpp/base/random.cpp:29:
/root/itpp-4.3.1/itpp/base/random_dsfmt.h: In static member function ‘static void itpp::random_details::DSFMT<MEXP, POS1, SL1, MSK1, MSK2, FIX1_V, FIX2_V, PCV1_V, PCV2_V>::do_recursion(typename itpp::random_details::DSFMT<MEXP, POS1, SL1, MSK1, MSK2, FIX1_V, FIX2_V, PCV1_V, PCV2_V>::Context::w128_t*, typename itpp::random_details::DSFMT<MEXP, POS1, SL1, MSK1, MSK2, FIX1_V, FIX2_V, PCV1_V, PCV2_V>::Context::w128_t*, typename itpp::random_details::DSFMT<MEXP, POS1, SL1, MSK1, MSK2, FIX1_V, FIX2_V, PCV1_V, PCV2_V>::Context::w128_t*, typename itpp::random_details::DSFMT<MEXP, POS1, SL1, MSK1, MSK2, FIX1_V, FIX2_V, PCV1_V, PCV2_V>::Context::w128_t*) [with int MEXP = 19937; int POS1 = 117; int SL1 = 19; long unsigned int MSK1 = 4498102069230399; long unsigned int MSK2 = 4501400546508797; long unsigned int FIX1_V = 10376655713290109737; long unsigned int FIX2_V = 4291106551315987578; long unsigned int PCV1_V = 4432916062321256576; long unsigned int PCV2_V = 1]’:
/root/itpp-4.3.1/itpp/base/random_dsfmt.h:306:17: error: the last argument must be an 8-bit immediate
     __m128i y = _mm_shuffle_epi32(lung->si, SSE2_SHUFF);
                 ^
itpp/CMakeFiles/itpp.dir/build.make:257: recipe for target 'itpp/CMakeFiles/itpp.dir/base/random.cpp.o' failed
make[2]: *** [itpp/CMakeFiles/itpp.dir/base/random.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'itpp/CMakeFiles/itpp.dir/all' failed
make[1]: *** [itpp/CMakeFiles/itpp.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
_____________________________

im running kali 2018. im sure im doing something wrong. ive never been able to get cmake make installs to work. im more of apt-get install guy. im still a NOOB to linux. 

PLEASE help me.

**Comment by szechyjs** [comment]
Not sure if this was your askubuntu post as well, but see my answer, it should solve your issue.

https://askubuntu.com/a/1050020/20730

`apt-get install libitpp-dev`

https://github.com/szechyjs/dsd/wiki/Installation#dependency-installation-on-ubuntu-1404-and-newer
