### ISSUE TITLE
DSD does not compile on Ubuntu 14.04

### ISSUE THREAD

**Issue by Rebel33** [szechyjs/dsd#49]
Hi,

Ubuntu 14.04 Linux version 3.13.0-39-generic , 
newest version mbelib and ittp were compiled and installed with no problem.
But dsd produces following failures: 

:~/DMR/szechyjs/dsd/build$ make
[  2%] Building C object CMakeFiles/dsd.dir/pa_devs.c.o
/DMR/szechyjs/dsd/pa_devs.c: In function ‘printPortAudioDevices’:
/DMR/szechyjs/dsd/pa_devs.c:14:5: error: unknown type name ‘PaStreamParameters’
     PaStreamParameters inputParameters, outputParameters;
     ^
/DMR/szechyjs/dsd/pa_devs.c:21:13: warning: format ‘%s’ expects argument of type ‘char _’, but argument 3 has type ‘int’ [-Wformat=]
             Pa_GetVersion(), Pa_GetVersionText() );
             ^
/DMR/szechyjs/dsd/pa_devs.c:45:52: error: ‘PaDeviceInfo’ has no member named ‘hostApi’
         else if( i == Pa_GetHostApiInfo( deviceInfo->hostApi )->defaultInputDevice )
                                                    ^
/DMR/szechyjs/dsd/pa_devs.c:47:13: error: unknown type name ‘PaHostApiInfo’
             const PaHostApiInfo *hostInfo = Pa_GetHostApiInfo( deviceInfo->hostApi );
             ^
/DMR/szechyjs/dsd/pa_devs.c:47:74: error: ‘PaDeviceInfo’ has no member named ‘hostApi’
             const PaHostApiInfo *hostInfo = Pa_GetHostApiInfo( deviceInfo->hostApi );
                                                                          ^
/DMR/szechyjs/dsd/pa_devs.c:48:51: error: request for member ‘name’ in something not a structure or union
             printf( "[ Default %s Input", hostInfo->name );
                                                   ^
/DMR/szechyjs/dsd/pa_devs.c:58:52: error: ‘PaDeviceInfo’ has no member named ‘hostApi’
         else if( i == Pa_GetHostApiInfo( deviceInfo->hostApi )->defaultOutputDevice )
                                                    ^
/DMR/szechyjs/dsd/pa_devs.c:60:13: error: unknown type name ‘PaHostApiInfo’
             const PaHostApiInfo *hostInfo = Pa_GetHostApiInfo( deviceInfo->hostApi );
             ^
/DMR/szechyjs/dsd/pa_devs.c:60:74: error: ‘PaDeviceInfo’ has no member named ‘hostApi’
             const PaHostApiInfo *hostInfo = Pa_GetHostApiInfo( deviceInfo->hostApi );
                                                                          ^
/DMR/szechyjs/dsd/pa_devs.c:62:51: error: request for member ‘name’ in something not a structure or union
             printf( " Default %s Output", hostInfo->name );
                                                   ^
/DMR/szechyjs/dsd/pa_devs.c:79:85: error: ‘PaDeviceInfo’ has no member named ‘hostApi’
         printf( "Host API                    = %s\n",  Pa_GetHostApiInfo( deviceInfo->hostApi )->name );
                                                                                     ^
/DMR/szechyjs/dsd/pa_devs.c:82:68: error: ‘PaDeviceInfo’ has no member named ‘defaultSampleRate’
         printf( "Default sample rate         = %8.2f\n", deviceInfo->defaultSampleRate );
                                                                    ^
make[2]: *_\* [CMakeFiles/dsd.dir/pa_devs.c.o] Fehler 1
make[1]: **\* [CMakeFiles/dsd.dir/all] Fehler 2
make: **\* [all] Fehler 2

I have no clue what can be done to solve this. Thanks a lot in advance for any help.

Fred
